# doesn't load wiktionary, because that's slow and often not needed

require_relative "file_util"
require_relative "string_util"
require_relative "debug"
require_relative "multistring"
require_relative "treebank"
require_relative "epos"
require_relative "genos"
require_relative "wiktionary"
require_relative "vlist"
require_relative "frequency"
require_relative "vocab_page"
require_relative "format_gloss"
require_relative "bilingual"
require_relative "illustrations"
require_relative "notes"
require_relative "latex"
require_relative "gloss"
require_relative "clown"
require_relative "tagzig"
require_relative "word"
require_relative "interlinear"
