require_relative "nouns"
require_relative "verbs"
require_relative "adjectives"
require_relative "lemma_util"
require_relative "writing"
require_relative "hop"
require_relative "prepositions"
require_relative "syllab"
